apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "restack.fullname" . }}-configmap
  labels:
    {{- include "restack.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/match: "true"
data:
{{- if .Values.envs }}
{{- range $key, $value := .Values.envs }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
