apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restack.fullname" . }}-secret
  labels:
    {{- include "restack.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/match: "true"
type: Opaque
data:
{{- if .Values.secrets }}
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
