apiVersion: v1
kind: Service
metadata:
  name: {{ include "restack.fullname" . }}
  labels:
    {{- include "restack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5233
      targetPort: 5233
      protocol: TCP
      name: engine-frontend
    - port: 6233
      targetPort: 6233
      protocol: TCP
      name: engine-api
      
  selector:
    {{- include "restack.selectorLabels" . | nindent 4 }}
