apiVersion: v1
kind: Service
metadata:
  name: {{ include "restack.fullname" . }}-stream
  labels:
    {{- include "restack.streamLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9233
      targetPort: 9233
      protocol: TCP
      name: stream
      
  selector:
    {{- include "restack.streamSelectorLabels" . | nindent 4 }}
