{{- if and .Values.observability.enabled .Values.observability.grafana.enabled .Values.observability.grafana.adminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restack.fullname" . }}-grafana-admin
  labels:
    {{- include "restack.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
type: Opaque
data:
  # Default user is admin
  GF_SECURITY_ADMIN_USER: {{ .Values.observability.grafana.adminUser | default "admin" | b64enc | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.observability.grafana.adminPassword | b64enc | quote }}
{{- end }} 