{{- if .Values.payloadCodec.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "restack.fullname" . }}-engine-codec
  labels:
    {{- include "restack.codecLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 12233
      targetPort: 12233
      protocol: TCP
      name: engine-codec
      
  selector:
    {{- include "restack.codecSelectorLabels" . | nindent 4 }}
{{- end }}
