apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "restack.fullname" . }}-engine-operator
  labels:
    {{- include "restack.operatorLabels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/search: "true"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "restack.operatorSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "restack.operatorSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "restack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-engine-operator
          envFrom:
            - configMapRef:
                name: {{ include "restack.fullname" . }}-configmap
            - secretRef:
                name: {{ include "restack.fullname" . }}-secret
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: ghcr.io/restackio/restack-operator-cloud:main
          imagePullPolicy: Always
          ports:
            - containerPort: 10233
              name: operator
          {{- if .Values.payloadCodec.enabled }}
          startupProbe:
            httpGet:
              path: /v2/health/head
              port: 12233
              host: localhost
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 3
            failureThreshold: 30  # Allow many failures during startup
          {{- end }}
          resources:
            limits:
              cpu: {{ .Values.operator.resources.cpu }}
              memory: {{ .Values.operator.resources.memory }}
            requests:
              cpu: {{ .Values.operator.resources.cpu }}
              memory: {{ .Values.operator.resources.memory }}

        {{- if .Values.logs.enabled }}
        # Sidecar container for logging
        - name: deployment-logs
          image: ghcr.io/restackio/k8s-logs-sidecar:main
          imagePullPolicy: Always
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEPLOYMENT_NAME
              value: {{ include "restack.fullname" . }}-engine-operator
            - name: GCS_BUCKET_NAME
              value: {{ .Values.logs.gcp.bucket }}
            - name: POD_SELECTOR
              value: {{ include "restack.name" . }}-operator
            - name: CONTAINER_LOGS_NAME
              value: {{ .Chart.Name }}-engine-operator
        {{- end }}
        
        {{- if .Values.payloadCodec.enabled }}
        # Sidecar container payload codec server
        - name: payload-codec-server
          image: ghcr.io/restackio/restack-payload-codec-cloud:main
          imagePullPolicy: Always
          ports:
            - containerPort: 12233
              name: payload-codec
          env:
            - name: GCS_BUCKET_NAME
              value: {{ .Values.logs.gcp.bucket }}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
