{{- if and .Values.pipeline.hpa.enabled .Values.pipeline.image.repository }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "restack.fullname" . }}-pipeline-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "restack.fullname" . }}-pipeline
  minReplicas: {{ .Values.pipeline.hpa.minReplicas }}
  maxReplicas: {{ .Values.pipeline.hpa.maxReplicas }}
  metrics:
    - type: ContainerResource
      containerResource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.pipeline.hpa.averageUtilization.cpu }}
        container: {{ .Chart.Name }}-pipeline
    - type: ContainerResource
      containerResource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.pipeline.hpa.averageUtilization.memory }}
        container: {{ .Chart.Name }}-pipeline
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0 # default value for scale up
      selectPolicy: Max # default value
      policies:
        - type: Pods
          value: 1 # default value for scale up
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 600 # default value for scale down
      selectPolicy: Max # default value
      policies:
        - type: Pods
          value: 1 # default value for scale down
          periodSeconds: 60
{{- end }}
