{{- if and .Values.observability.enabled .Values.observability.prometheus.enabled .Values.observability.prometheus.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "restack.fullname" . }}-prometheus
  labels:
    {{- include "restack.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "restack.fullname" . }}-prometheus
  labels:
    {{- include "restack.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "restack.fullname" . }}-prometheus
  labels:
    {{- include "restack.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "restack.fullname" . }}-prometheus
subjects:
  - kind: ServiceAccount
    name: {{ include "restack.fullname" . }}-prometheus
    namespace: {{ .Release.Namespace }}
{{- end }} 